import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  id: {
    welcome: "Selamat Datang",
    dashboard: "Dashboard",
    transactions: "Transaksi",
    wallets: "Dompet",
    budgets: "Anggaran",
    reports: "Laporan",
    settings: "Pengaturan",
    profile: "Profil",
    logout: "Keluar",
    login: "Masuk",
    register: "Daftar",
    email: "Email",
    password: "Password",
    name: "Nama Lengkap",
    save: "Simpan",
    cancel: "Batal",
    delete: "Hapus",
    edit: "Edit",
    theme: "Tema",
    language: "Bahasa",
    currency: "Mata Uang",
    light: "Terang",
    dark: "Gelap",
    hacker: "Hacker",
    total_balance: "Total Saldo",
    income: "Pemasukan",
    expense: "Pengeluaran",
    recent_transactions: "Transaksi Terakhir",
    no_transactions: "Belum ada transaksi",
    add_transaction: "Tambah Transaksi",
    upload_photo: "Unggah Foto",
    change_password: "Ganti Password",
    current_password: "Password Saat Ini",
    new_password: "Password Baru",
    confirm_password: "Konfirmasi Password",
    forgot_password: "Lupa Password?",
    reset_password: "Reset Password",
    proof_image: "Bukti Transaksi",
    upload_proof: "Unggah Bukti",
    view_proof: "Lihat Bukti",
    transaction_proof: "Bukti Transaksi",
    description: "Keterangan",
    date: "Tanggal",
    category: "Kategori",
    account: "Akun",
    amount: "Jumlah",
    type: "Tipe",
  },
  en: {
    welcome: "Welcome",
    dashboard: "Dashboard",
    transactions: "Transactions",
    wallets: "Wallets",
    budgets: "Budgets",
    reports: "Reports",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Full Name",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    theme: "Theme",
    language: "Language",
    currency: "Currency",
    light: "Light",
    dark: "Dark",
    hacker: "Hacker",
    total_balance: "Total Balance",
    income: "Income",
    expense: "Expense",
    recent_transactions: "Recent Transactions",
    no_transactions: "No transactions yet",
    add_transaction: "Add Transaction",
    upload_photo: "Upload Photo",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    forgot_password: "Forgot Password?",
    reset_password: "Reset Password",
    proof_image: "Transaction Proof",
    upload_proof: "Upload Proof",
    view_proof: "View Proof",
    transaction_proof: "Transaction Proof",
    description: "Description",
    date: "Date",
    category: "Category",
    account: "Account",
    amount: "Amount",
    type: "Type",
  },
  ar: {
    welcome: "أهلاً بك",
    dashboard: "لوحة التحكم",
    transactions: "المعاملات",
    wallets: "المحافظ",
    budgets: "الميزانيات",
    reports: "التقارير",
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    name: "الاسم الكامل",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    theme: "المظهر",
    language: "اللغة",
    currency: "العملة",
    light: "فاتح",
    dark: "داكن",
    hacker: "هاكر",
    total_balance: "إجمالي الرصيد",
    income: "دخل",
    expense: "مصروف",
    recent_transactions: "أحدث المعاملات",
    no_transactions: "لا توجد معاملات بعد",
    add_transaction: "إضافة معاملة",
    upload_photo: "رفع صورة",
    change_password: "تغيير كلمة المرور",
    current_password: "كلمة المرور الحالية",
    new_password: "كلمة المرور الجديدة",
    confirm_password: "تأكيد كلمة المرور",
    forgot_password: "نسيت كلمة المرور؟",
    reset_password: "إعادة تعيين كلمة المرور",
    proof_image: "إثبات المعاملة",
    upload_proof: "رفع إثبات",
    view_proof: "عرض الإثبات",
    transaction_proof: "إثبات المعاملة",
    description: "الوصف",
    date: "التاريخ",
    category: "التصنيف",
    account: "الحساب",
    amount: "المبلغ",
    type: "النوع",
  },
  zh: {
    welcome: "欢迎",
    dashboard: "仪表盘",
    transactions: "交易",
    wallets: "钱包",
    budgets: "预算",
    reports: "报表",
    settings: "设置",
    profile: "个人资料",
    logout: "退出",
    login: "登录",
    register: "注册",
    email: "电子邮件",
    password: "密码",
    name: "全名",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    theme: "主题",
    language: "语言",
    currency: "货币",
    light: "浅色",
    dark: "深色",
    hacker: "黑客",
    total_balance: "总余额",
    income: "收入",
    expense: "支出",
    recent_transactions: "最近交易",
    no_transactions: "暂无交易",
    add_transaction: "添加交易",
    upload_photo: "上传照片",
    change_password: "修改密码",
    current_password: "当前密码",
    new_password: "新密码",
    confirm_password: "确认密码",
    forgot_password: "忘记密码？",
    reset_password: "重置密码",
    proof_image: "交易凭证",
    upload_proof: "上传凭证",
    view_proof: "查看凭证",
    transaction_proof: "交易凭证",
    description: "描述",
    date: "日期",
    category: "分类",
    account: "账户",
    amount: "金额",
    type: "类型",
  },
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "id";
  });

  const [dir, setDir] = useState("ltr");

  useEffect(() => {
    localStorage.setItem("language", language);
    setDir(language === "ar" ? "rtl" : "ltr");
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};
